server:
  port: 8081
spring:
  rabbitmq:   
    host: ${mq-host:localhost}
    port: $(mq-port:5672}
    username: ${mq-username:guest}
    password: ${mq-password:guest}
    virtual-host: ${mq-vhost}
    request:     
      exchange:
        name: ${exchange}
